### ISSUE TITLE
Url failed to download

### ISSUE THREAD

**Issue by dayn9t** [master-technology/AssetManagerStudio#29]
Asset Manager Studio version: v0.0.24
OS: Ubuntu 22.04
Assets: https://www.unrealengine.com/marketplace/en-US/product/b82c47ddbaf74a63adea3001ce44c3ac
Outpus:

Total files to download 209 Size 210067154 D/L Threads 4
url failed to download http://epicgames-download1-1251447533.file.myqcloud.com/Builds/Rocket/Automated/Stylizedc5eba030d95dV1/CloudDir/ChunksV3/21/7C9EB893734CB84B_5104202EA74FD69E0F9F02BEE84FAD22.chunk
(node:386927) UnhandledPromiseRejectionWarning: Error: Failed to download '7C9EB893734CB84B_5104202EA74FD69E0F9F02BEE84FAD22.chunk': Request failed with status '302'
    at yt.loadData (/tmp/.mount_asset-u9sqqa/resources/app.asar/out/main/chunks/Manifest-5bc2b61e.js:21:18399)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async bt._read (/tmp/.mount_asset-u9sqqa/resources/app.asar/out/main/chunks/Manifest-5bc2b61e.js:21:19557)
(Use `asset-manager-studio --trace-warnings ...` to show where the warning was created)
(node:386927) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by NathanaelA** [comment]
This code should have been fixed in v0.26 or v0.27 -- please let me know if you have any further issues.
