### ISSUE TITLE
Error: /lib64/libc.so.6: version `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by MalikuMane** [master-technology/AssetManagerStudio#7]
Attempting to run on openSUSE Leap 15.4 (glibc-2.31). same error on appimage and an extracted deb.

Error: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /run/user/1067/.mount_asset-YqZEcE/resources/better_sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1326:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:937:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at new z (/run/user/1067/.mount_asset-YqZEcE/resources/app.asar/out/main/chunks/better-sqlite3-a6746100.js:1:5865)
    at new O (/run/user/1067/.mount_asset-YqZEcE/resources/app.asar/out/main/chunks/Manifest-30660f44.js:1:3236)

**Comment by NathanaelA** [comment]
Please retry downloading v0.0.14 -- I believe the new upload should fix the issue.
