### ISSUE TITLE
Flatpak version has file access issues with settings

### ISSUE THREAD

**Issue by sna-scourtney** [master-technology/AssetManagerStudio#71]
I've been running with a manual install on the previous version, but with 0.0.27 I moved to Flatpak. The installation worked fine, and I'm able to run the app, but when I change the user settings for project paths, engine base directory, and vault paths, the settings are accepted but apparently not stored to disk.

This could be due to the "sandboxing" behavior of Flatpak, and I probably need to grant permissions for it to write its settings in my home directory.

The log contains nothing pertinent to the saving of settings (as far as I can tell), but it is clear from the following messages that it took my vault setting during the session even though it didn't persist:

```
[ Worker ] [Vault Scanner] Scanning for vault items in /usr/local/share/ue_vault/
Error occurred in handler for 'getSettingsConfig': Error: ENOENT: no such file or directory, mkdir '/usr/local/share/ue_vault/'
    at Object.mkdirSync (node:fs:1371:26)
    at Object.getVaultDir (/app/asset-manager-studio/resources/app.asar/out/main/index.js:2:201709)
    at /app/asset-manager-studio/resources/app.asar/out/main/index.js:2:283975
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:87037)
    at WebContents.emit (node:events:518:28) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/usr/local/share/ue_vault/'
}
```

The directory /usr/local/share/ue_vault/ definitely exists and is owned by my user account, permissions 755. AMS shouldn't be trying to create the directory, but I suspect what's really happening here is that the Flatpak sandbox isn't allowing it to read the parent, hence the "ENOENT" result.

I'll take a look at the code and see if I can provide further diagnostics.

**Comment by sna-scourtney** [comment]
Update: It appears this is related to Flatpak treating /usr and its subdirectories as system-reserved. I can get past the error in the above log by specifying /home/MYUSER/ue_vault/ instead of /usr/local/share/ue_vault/. I may have to move my vault to /srv/ue_vault/ because /srv/ is not treated as reserved by Flatpak.

I've further found that the error was causing the settings not to be saved.

To access directories outside the sandbox, I am running with a command of this form:

```
$ flatpak run --filesystem=home --filesystem=/SOME/OTHER/PATH studio.assetmanager.ams
```

The --filesystem option can be repeated.

If all the needed directories are in the list applicable to the "host" keyword, this version (which I have tested) is shorter:

```
$ flatpak run --filesystem=host studio.assetmanager.ams
```

**Comment by sna-scourtney** [comment]
To summarize the debugging so far, I think this is a documentation and possibly an error message issue, not a code bug. It would help in the documentation to mention the possible need for granting file access outside the sandbox, depending on where engine, project, and vault directories are located on your system. When the code encounters an access violation, it might be useful to mention this requirement in the message. I'm not sure if this would require a call to stat() on the path rather than just attempting to open it, to get more specific info from the o.s.

**Comment by NathanaelA** [comment]
Well, in the Flatpak, I've already asked for `--filesystem=host` --- doing some research according to the security system `/usr` is not included in `host`.   https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access --  I would have to also ask for `host-os` if I wanted access to it, and I feel like that probably would make others uncomfortable.            

So you are correct it is documentation issue, and an error message issue as the mkdir is used to make the very last `vault` path so that d/l's work (since all new d/l's go to the last vault path you have put in).  

I'll catch the error in the next version and display a better error message to let people know what is going on if they also have their vault under `/usr`.    Please note, most people put their vault directory inside their home directory, any reason you put yours under `/usr/local`

**Comment by sna-scourtney** [comment]
> Well, in the Flatpak, I've already asked for `--filesystem=host` --- doing some research according to the security system `/usr` is not included in `host`. https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access -- I would have to also ask for `host-os` if I wanted access to it, and I feel like that probably would make others uncomfortable.
[snip] 
>  Please note, most people put their vault directory inside their home directory, any reason you put yours under `/usr/local`

I agree that it would not be good to have "host-os" as a default permission. I didn't realize you had "host" already, so I probably don't need it on my command line. Recall that my testing initially had the vault at /usr/local/share/ue_vault/, but I have now moved it to /srv/ue_vault/ which is included in "host".

The choice of /usr/local/share/ vs. /srv/ for a parent directory of the vault was mostly arbitrary. I don't want it in my home directory because it's quite large, and my home directory is already pretty time-consuming to back up. Yes, I could do a mount point somewhere under $HOME, but I really don't like those because it too closely couples system startup behavior (a mount point in /etc/fstab) with a specific user account. I'm used to multiuser servers, so I tend to think in those terms even on my workstation.

All that said, /srv/ue_vault/ is working just fine for me, now that I know anything under /usr/ will be problematic. I think we're in agreement this is just a documentation issue, and I apologize for not realizing that at first. I don't use very many Flatpak apps and was only passingly familiar with its permissions behavior.
